const { PrismaClient } = require("@prisma/client");
const prisma = new PrismaClient();

async function main() {
  await prisma.recipe.deleteMany({});
  await prisma.dish.deleteMany({});
  await prisma.ingredient.deleteMany({});
  await prisma.type.deleteMany({});
  await prisma.country.deleteMany({});
  await prisma.tag.deleteMany({});
  await prisma.user.deleteMany({});
  await prisma.region.deleteMany({});
  await prisma.unit.deleteMany({});

  const john = await prisma.user.create({
    data: {
      name: "john",
      email: "john.doe@yopmail.com",
      isadmin: true,
      password: "johndoe",
    },
  });

  const afrique = await prisma.region.create({
    data: {
      name: "Afrique",
    },
  });

  const maroc = await prisma.country.create({
    data: { name: "Maroc" },
  });

  const countries = [
    { name: "Albanie" },
    { name: "Antarctique" },
    { name: "Algérie" },
    { name: "Samoa Américaines" },
    { name: "Andorre" },
    { name: "Angola" },
    { name: "Antigua-et-Barbuda" },
    { name: "Azerbaïdjan" },
    { name: "Argentine" },
    { name: "Australie" },
    { name: "Autriche" },
    { name: "Bahamas" },
    { name: "Bahreïn" },
    { name: "Bangladesh" },
    { name: "Arménie" },
    { name: "Barbade" },
    { name: "Belgique" },
    { name: "Bermudes" },
    { name: "Bhoutan" },
    { name: "Bolivie" },
    { name: "Bosnie-Herzégovine" },
    { name: "Botswana" },
    { name: "Île Bouvet" },
    { name: "Brésil" },
    { name: "Belize" },
    { name: "Territoire Britannique de l'Océan Indien" },
    { name: "Îles Salomon" },
    { name: "Îles Vierges Britanniques" },
    { name: "Brunéi Darussalam" },
    { name: "Bulgarie" },
    { name: "Myanmar" },
    { name: "Burundi" },
    { name: "Bélarus" },
    { name: "Cambodge" },
    { name: "Cameroun" },
    { name: "Canada" },
    { name: "Cap-vert" },
    { name: "Îles Caïmanes" },
    { name: "République Centrafricaine" },
    { name: "Sri Lanka" },
    { name: "Tchad" },
    { name: "Chili" },
    { name: "Chine" },
    { name: "Taïwan" },
    { name: "Île Christmas" },
    { name: "Îles Cocos (Keeling)" },
    { name: "Colombie" },
    { name: "Comores" },
    { name: "Mayotte" },
    { name: "République du Congo" },
    { name: "République Démocratique du Congo" },
    { name: "Îles Cook" },
    { name: "Costa Rica" },
    { name: "Croatie" },
    { name: "Cuba" },
    { name: "Chypre" },
    { name: "République Tchèque" },
    { name: "Bénin" },
    { name: "Danemark" },
    { name: "Dominique" },
    { name: "République Dominicaine" },
    { name: "Équateur" },
    { name: "El Salvador" },
    { name: "Guinée Équatoriale" },
    { name: "Éthiopie" },
    { name: "Érythrée" },
    { name: "Estonie" },
    { name: "Îles Féroé" },
    { name: "Îles (malvinas) Falkland" },
    { name: "Géorgie du Sud et les Îles Sandwich du Sud" },
    { name: "Fidji" },
    { name: "Finlande" },
    { name: "Îles Åland" },
    { name: "France" },
    { name: "Guyane Française" },
    { name: "Polynésie Française" },
    { name: "Terres Australes Françaises" },
    { name: "Djibouti" },
    { name: "Gabon" },
    { name: "Géorgie" },
    { name: "Gambie" },
    { name: "Territoire Palestinien Occupé" },
    { name: "Allemagne" },
    { name: "Ghana" },
    { name: "Gibraltar" },
    { name: "Kiribati" },
    { name: "Grèce" },
    { name: "Groenland" },
    { name: "Grenade" },
    { name: "Guadeloupe" },
    { name: "Guam" },
    { name: "Guatemala" },
    { name: "Guinée" },
    { name: "Guyana" },
    { name: "Haïti" },
    { name: "Îles Heard et Mcdonald" },
    { name: "Saint-Siège (état de la Cité du Vatican)" },
    { name: "Honduras" },
    { name: "Hong-Kong" },
    { name: "Hongrie" },
    { name: "Islande" },
    { name: "Inde" },
    { name: "Indonésie" },
    { name: "République Islamique d'Iran" },
    { name: "Iraq" },
    { name: "Irlande" },
    { name: "Israël" },
    { name: "Italie" },
    { name: "Côte d'Ivoire" },
    { name: "Jamaïque" },
    { name: "Japon" },
    { name: "Kazakhstan" },
    { name: "Jordanie" },
    { name: "Kenya" },
    { name: "République Populaire Démocratique de Corée" },
    { name: "République de Corée" },
    { name: "Koweït" },
    { name: "Kirghizistan" },
    { name: "République Démocratique Populaire Lao" },
    { name: "Liban" },
    { name: "Lesotho" },
    { name: "Lettonie" },
    { name: "Libéria" },
    { name: "Jamahiriya Arabe Libyenne" },
    { name: "Liechtenstein" },
    { name: "Lituanie" },
    { name: "Luxembourg" },
    { name: "Macao" },
    { name: "Madagascar" },
    { name: "Malawi" },
    { name: "Malaisie" },
    { name: "Maldives" },
    { name: "Mali" },
    { name: "Malte" },
    { name: "Martinique" },
    { name: "Mauritanie" },
    { name: "Maurice" },
    { name: "Mexique" },
    { name: "Monaco" },
    { name: "Mongolie" },
    { name: "République de Moldova" },
    { name: "Montserrat" },
    { name: "Maroc" },
    { name: "Mozambique" },
    { name: "Oman" },
    { name: "Namibie" },
    { name: "Nauru" },
    { name: "Népal" },
    { name: "Pays-Bas" },
    { name: "Antilles Néerlandaises" },
    { name: "Aruba" },
    { name: "Nouvelle-Calédonie" },
    { name: "Vanuatu" },
    { name: "Nouvelle-Zélande" },
    { name: "Nicaragua" },
    { name: "Niger" },
    { name: "Nigéria" },
    { name: "Niué" },
    { name: "Île Norfolk" },
    { name: "Norvège" },
    { name: "Îles Mariannes du Nord" },
    { name: "Îles Mineures Éloignées des États-Unis" },
    { name: "États Fédérés de Micronésie" },
    { name: "Îles Marshall" },
    { name: "Palaos" },
    { name: "Pakistan" },
    { name: "Panama" },
    { name: "Papouasie-Nouvelle-Guinée" },
    { name: "Paraguay" },
    { name: "Pérou" },
    { name: "Philippines" },
    { name: "Pitcairn" },
    { name: "Pologne" },
    { name: "Portugal" },
    { name: "Guinée-Bissau" },
    { name: "Timor-Leste" },
    { name: "Porto Rico" },
    { name: "Qatar" },
    { name: "Réunion" },
    { name: "Roumanie" },
    { name: "Fédération de Russie" },
    { name: "Rwanda" },
    { name: "Sainte-Hélène" },
    { name: "Saint-Kitts-et-Nevis" },
    { name: "Anguilla" },
    { name: "Sainte-Lucie" },
    { name: "Saint-Pierre-et-Miquelon" },
    { name: "Saint-Vincent-et-les Grenadines" },
    { name: "Saint-Marin" },
    { name: "Sao Tomé-et-Principe" },
    { name: "Arabie Saoudite" },
    { name: "Sénégal" },
    { name: "Seychelles" },
    { name: "Sierra Leone" },
    { name: "Singapour" },
    { name: "Slovaquie" },
    { name: "Viet Nam" },
    { name: "Slovénie" },
    { name: "Somalie" },
    { name: "Afrique du Sud" },
    { name: "Zimbabwe" },
    { name: "Espagne" },
    { name: "Sahara Occidental" },
    { name: "Soudan" },
    { name: "Suriname" },
    { name: "Svalbard etÎle Jan Mayen" },
    { name: "Swaziland" },
    { name: "Suède" },
    { name: "Suisse" },
    { name: "République Arabe Syrienne" },
    { name: "Tadjikistan" },
    { name: "Thaïlande" },
    { name: "Togo" },
    { name: "Tokelau" },
    { name: "Tonga" },
    { name: "Trinité-et-Tobago" },
    { name: "Émirats Arabes Unis" },
    { name: "Tunisie" },
    { name: "Turquie" },
    { name: "Turkménistan" },
    { name: "Îles Turks et Caïques" },
    { name: "Tuvalu" },
    { name: "Ouganda" },
    { name: "Ukraine" },
    { name: "Macédoine" },
    { name: "Égypte" },
    { name: "Royaume-Uni" },
    { name: "Île de Man" },
    { name: "République-Unie de Tanzanie" },
    { name: "États-Unis" },
    { name: "Îles Vierges des États-Unis" },
    { name: "Burkina Faso" },
    { name: "Uruguay" },
    { name: "Ouzbékistan" },
    { name: "Venezuela" },
    { name: "Wallis et Futuna" },
    { name: "Samoa" },
    { name: "Yémen" },
    { name: "Serbie-et-Monténégro" },
    { name: "Zambie" },
  ];

  const regions = [
    { name: "Amérique du Sud" },
    { name: "Amérique du Nord" },
    { name: "Amérique du Sud" },
    { name: "Afrique de l'Ouest" },
    { name: "Afrique Centrale" },
    { name: "Afrique de l'Est" },
    { name: "Afrique du Sud" },
    { name: "Europe de l'Est" },
    { name: "Europe Centrale" },
    { name: "Europe du Sud" },
    { name: "Europe de l'Ouest" },
    { name: "Europe du Nord" },
    { name: "Asie de l'Est" },
    { name: "Asie du Sud" },
    { name: "Asie Centrale" },
    { name: "Asie du Sud Est" },
    { name: "Asie de l'Ouest" },
    { name: "Asie du Nord" },
    { name: "Océanie" },
    { name: "Arctique" },
    { name: "Antartique" },
  ];

  const tags = [
    { name: "Sans Allergène" },
    { name: "Sans Sucre" },
    { name: "Sans Gluten" },
    { name: "Sans Sel" },
    { name: "Végan" },
    { name: "Végétarien" },
    { name: "Végétarien Indien" },
    { name: "Halal" },
    { name: "Casher" },
    { name: "Hindou" },
    { name: "Bébé" },
    { name: "Enfant" },
    { name: "Piquant" },
    { name: "Sucré" },
    { name: "Très Gras" },
    { name: "Pornfood" },
    { name: "Instafood" },
  ];

  const ingredients = [
    { name: "Angélique" },
    { name: "Chou Savoie" },
    { name: "Tilleul d'argent" },
    { name: "kiwi" },
    { name: "Allium" },
    { name: "Oignon de jardin" },
    { name: "Semblait" },
    { name: "Ail" },
    { name: "Ciboulette" },
    { name: "Lemon Verbena" },
    { name: "Noix de cajou" },
    { name: "Ananas" },
    { name: "aneth" },
    { name: "Crème anglaise" },
    { name: "Céleri sauvage" },
    { name: "Cacahuète" },
    { name: "Bardane" },
    { name: "Raifort" },
    { name: "Estragon" },
    { name: "Mugwort" },
    { name: "Asperges" },
    { name: "Avoine" },
    { name: "Carambole" },
    { name: "Noix du Brésil" },
    { name: "Betterave" },
    { name: "Bourrache" },
    { name: "Moutarde chinoise" },
    { name: "Suédois" },
    { name: "Râpé" },
    { name: "Chou commun" },
    { name: "Chou fleur" },
    { name: "Choux de Bruxelles" },
    { name: "Kohlrabi" },
    { name: "Brocoli" },
    { name: "chou chinois" },
    { name: "Navet" },
    { name: "Pois de pigeon" },
    { name: "Thé" },
    { name: "câpres" },
    { name: "Poivre" },
    { name: "Papaye" },
    { name: "Carthame" },
    { name: "Carvi" },
    { name: "Noix de pécan" },
    { name: "châtaigne" },
    { name: "Camomille romaine" },
    { name: "Pois chiche" },
    { name: "Endive" },
    { name: "Chicorée" },
    { name: "Cannelle chinoise" },
    { name: "Ceylan cannelle" },
    { name: "Pastèque" },
    { name: "Chaux" },
    { name: "Citron" },
    { name: "Pommade" },
    { name: "Mandarine" },
    { name: "Clémentine" },
    { name: "Orange" },
    { name: "Café" },
    { name: "Café arabica" },
    { name: "Café robuste" },
    { name: "Coriandre" },
    { name: "Noisette commune" },
    { name: "Safran" },
    { name: "Cantaloup" },
    { name: "Concombre" },
    { name: "Cucurbita" },
    { name: "Cumin" },
    { name: "Curcuma" },
    { name: "Quinze" },
    { name: "Citronnelle" },
    { name: "Globe artichaut" },
    { name: "Carotte sauvage" },
    { name: "Point de vue japonais" },
    { name: "Cardamome" },
    { name: "Corde noire" },
    { name: "Loquat" },
    { name: "Pomme de cire" },
    { name: "Sarrasin commun" },
    { name: "Tartariat sarrasin" },
    { name: "Figure" },
    { name: "Fenouil" },
    { name: "fraise" },
    { name: "Huckleberry noir" },
    { name: "Je suis haricot" },
    { name: "Tournesol" },
    { name: "Boucle de mer" },
    { name: "Orge" },
    { name: "Hysope" },
    { name: "Anis étoilé" },
    { name: "Chou" },
    { name: "Patate douce" },
    { name: "Noyer noir" },
    { name: "Noyer commun" },
    { name: "Salade" },
    { name: "Pois d'herbe" },
    { name: "Petite baie" },
    { name: "Lentilles" },
    { name: "Cresson de jardin" },
    { name: "Lovage" },
    { name: "La graine de lin" },
    { name: "Organo mexicain" },
    { name: "Lichee" },
    { name: "Lupin" },
    { name: "Pomme" },
    { name: "Mangue" },
    { name: "Camomille allemande" },
    { name: "Mélisse" },
    { name: "Mentha" },
    { name: "Menthe orange" },
    { name: "Maïs" },
    { name: "Menthe verte" },
    { name: "Menthe poivrée" },
    { name: "Néflier" },
    { name: "Gourde amère" },
    { name: "Mûre" },
    { name: "Mûrier noir" },
    { name: "Noix de muscade" },
    { name: "Basilic doux" },
    { name: "Primrose de soirée" },
    { name: "olive" },
    { name: "Marjolain doux" },
    { name: "Peut marjolien" },
    { name: "Organo commun" },
    { name: "Riz" },
    { name: "Gens" },
    { name: "Coquelicot" },
    { name: "Fruit de la passion" },
    { name: "Panais" },
    { name: "Avocat" },
    { name: "Persil" },
    { name: "Haricot écarlate" },
    { name: "Cinq haricots" },
    { name: "Haricot commun" },
    { name: "Date" },
    { name: "Solitaire noire" },
    { name: "Anis" },
    { name: "Pignon de pin" },
    { name: "Poivre (épice)" },
    { name: "Pistache" },
    { name: "Pois commun" },
    { name: "Purslane" },
    { name: "Prunus (cerise, prune)" },
    { name: "Abricot" },
    { name: "Cerise sucrée" },
    { name: "Cerise aigre" },
    { name: "Prune européenne" },
    { name: "Amande" },
    { name: "La pêche" },
    { name: "Goyave" },
    { name: "Grenade" },
    { name: "Poire" },
    { name: "Un radis" },
    { name: "Rhubarbe de jardin" },
    { name: "Cassis" },
    { name: "Groseille" },
    { name: "Groseille à maquereau" },
    { name: "Cresson" },
    { name: "Romarin" },
    { name: "Rubus (Blackberry, framboise)" },
    { name: "Clougier" },
    { name: "Framboise rouge" },
    { name: "Framboise noire" },
    { name: "Oseille" },
    { name: "Sauge commune" },
    { name: "Sureau noir" },
    { name: "Salé d'été" },
    { name: "Savoureux hiver" },
    { name: "Seigle" },
    { name: "Sésame" },
    { name: "Jardin tomate" },
    { name: "tomate cerise" },
    { name: "Tomate de jardin (était.)" },
    { name: "Aubergine" },
    { name: "Pomme de terre" },
    { name: "Rond-point" },
    { name: "Sorgho" },
    { name: "Épinard" },
    { name: "Clous de girofle" },
    { name: "Tamarin" },
    { name: "Pissenlit" },
    { name: "Fève de cacao" },
    { name: "Thym commun" },
    { name: "Tilleul" },
    { name: "Tilleul de petite feuille" },
    { name: "Fenugrec" },
    { name: "Blé commun" },
    { name: "Vaccinium (myrtille, canneberge, huckleberry)" },
    { name: "Myrtille lowbush" },
    { name: "Sparkleberry" },
    { name: "Myrtille highbush" },
    { name: "Canneberge américaine" },
    { name: "Myrtille" },
    { name: "Lingonfoint" },
    { name: "Vanille" },
    { name: "Verveine commune" },
    { name: "Fève" },
    { name: "Haricot adzuki" },
    { name: "Haricot gram" },
    { name: "Seulement haricot" },
    { name: "Haricot d'escalade" },
    { name: "Niébé" },
    { name: "Raisin de muscadine" },
    { name: "Cépage commun" },
    { name: "Maïs" },
    { name: "Gingembre" },
    { name: "Blackberry arctique" },
    { name: "banane" },
    { name: "Bayberry" },
    { name: "Myrtille d'Elliott" },
    { name: "Blueberry du Canada" },
    { name: "Carrosserie" },
    { name: "Cassis de buffle" },
    { name: "Céleria" },
    { name: "Branches de céleri" },
    { name: "Ciboulette chinoise" },
    { name: "Canneberge européenne" },
    { name: "Creerberry" },
    { name: "Ginseng" },
    { name: "Cascade huckleberry" },
    { name: "Hunkleberry ovale-feuille" },
    { name: "Smuckleberry Evergreen" },
    { name: "Huckleberry rouge" },
    { name: "Long" },
    { name: "Noix de macadamia (M. Tetraphylla)" },
    { name: "Oignon de jardin (var.)" },
    { name: "Raisin d'été" },
    { name: "Nectarines" },
    { name: "Pêche (était.)" },
    { name: "Poivre" },
    { name: "Ramboutan" },
    { name: "riz rouge" },
    { name: "Riz sauvage" },
    { name: "Noix japonaise" },
    { name: "Oignon gallois" },
    { name: "Blé dur" },
    { name: "Échalote" },
    { name: "Salade de fusée" },
    { name: "Carotte" },
    { name: "Triticale" },
    { name: "Chou noir" },
    { name: "Myrtille demi-hauteur" },
    { name: "Feuilles de céleri" },
    { name: "Feuilles de chicorée" },
    { name: "Komatsuna" },
    { name: "Thé PAK" },
    { name: "Chou de napa" },
    { name: "Racines de chicorée" },
    { name: "Pamplemousse / Pummelo Hybrid" },
    { name: "Pamplemousse" },
    { name: "Jostabréry" },
    { name: "Kai-lan" },
    { name: "Organo italien" },
    { name: "Chou des oxfeuilles" },
    { name: "Radis daikon" },
    { name: "radis noir" },
    { name: "Radis (var.)" },
    { name: "Betterave rouge" },
    { name: "Doux rowanberry" },
    { name: "Sage PineApple" },
    { name: "Cassis" },
    { name: "Bière" },
    { name: "Autre pain" },
    { name: "Céréales pour le petit déjeuner" },
    { name: "Autre produit de soja" },
    { name: "Autre produit de céréales" },
    { name: "Courrier" },
    { name: "Biscuit" },
    { name: "Levain" },
    { name: "Esprit" },
    { name: "Vin fortifié" },
    { name: "Autres boissons alcoolisées" },
    { name: "Ormeau" },
    { name: "Abiach" },
    { name: "Acerola" },
    { name: "Gland" },
    { name: "Courge d'hiver" },
    { name: "Pour que" },
    { name: "Crabe roi rouge" },
    { name: "Luzerne." },
    { name: "Totalité" },
    { name: "Amarante" },
    { name: "Pointe de flèche" },
    { name: "Marante" },
    { name: "poire asiatique" },
    { name: "Hareng de l'Atlantique" },
    { name: "Mackérienne de l'Atlantique" },
    { name: "Peint peint" },
    { name: "Pollock de l'Atlantique" },
    { name: "Atlantique Wolffish" },
    { name: "Pousses de bambou" },
    { name: "Basse rayée" },
    { name: "Noix de hêtres" },
    { name: "Béluga" },
    { name: "Bison" },
    { name: "Noire de l'Alaska" },
    { name: "Crabe bleu" },
    { name: "Moules bleue" },
    { name: "Tuna du Nord de Bluefin" },
    { name: "Poisson bleu" },
    { name: "Sanglier" },
    { name: "Baleine boréale" },
    { name: "Fruit à pain" },
    { name: "Graine d'arbre de miel" },
    { name: "Rapini" },
    { name: "Buffle" },
    { name: "Lotte" },
    { name: "Butterbur géant" },
    { name: "Poisson-bébé américain" },
    { name: "Désagréable" },
    { name: "Courge butternut" },
    { name: "Calebasse" },
    { name: "Cardon" },
    { name: "Prune natale" },
    { name: "Caroube" },
    { name: "Carpe commune" },
    { name: "Manioc" },
    { name: "Poisson-chat de canal" },
    { name: "Chayote" },
    { name: "Cherimoya" },
    { name: "Cerfeuil" },
    { name: "Partager" },
    { name: "Poulet" },
    { name: "brocoli chinois" },
    { name: "Châtaigne chinois" },
    { name: "Châtaigne d'eau chinoise" },
    { name: "Guirlande chrysanthème" },
    { name: "Cisco" },
    { name: "Coûte de noisette" },
    { name: "Noix de coco" },
    { name: "Cod du Pacifique" },
    { name: "Cod de l'Atlantique" },
    { name: "Pieuvre commune" },
    { name: "Salade de maïs" },
    { name: "Coton" },
    { name: "Pois de cajang" },
    { name: "Malus (pomme de crabe)" },
    { name: "Squashberry" },
    { name: "Atlantic Croker" },
    { name: "Coussin" },
    { name: "Seiche" },
    { name: "Cerf mule" },
    { name: "Diablefish" },
    { name: "Mais" },
    { name: "Poisson dauphin" },
    { name: "Tambour d'eau douce" },
    { name: "le canard colvert" },
    { name: "Crabe de densité" },
    { name: "Durian" },
    { name: "Huître orientale" },
    { name: "Anguille d'eau douce" },
    { name: "Sureau" },
    { name: "Chaque" },
    { name: "Émeu" },
    { name: "Oregon Yampah" },
    { name: "Anchois européen" },
    { name: "Châtaignier européen" },
    { name: "Turbot" },
    { name: "Feu de feu" },
    { name: "Floride Pompano" },
    { name: "Noix de ginkgo" },
    { name: "Oie cendrée" },
    { name: "Grain de raisin" },
    { name: "Groenland Halibut / Turbot" },
    { name: "Sécréteur" },
    { name: "Groupeur" },
    { name: "Guinée" },
    { name: "Églefin" },
    { name: "Hippoglossus (Halibut commun)" },
    { name: "Noisette" },
    { name: "Noix de hickory" },
    { name: "Cheval" },
    { name: "Arbre raiforteur" },
    { name: "Alaska myrtille" },
    { name: "Hyacinthe" },
    { name: "mousse irlandaise" },
    { name: "Pacific Jack Mackerel" },
    { name: "Jackfruit" },
    { name: "Châtaignier japonais" },
    { name: "Prune Java" },
    { name: "topinambour" },
    { name: "Jujube" },
    { name: "Jute" },
    { name: "Autre" },
    { name: "Varech" },
    { name: "roi mackerel" },
    { name: "Kumquat" },
    { name: "Agneauquarters" },
    { name: "Chiton en cuir" },
    { name: "Poireau sauvage" },
    { name: "Ling commun" },
    { name: "Homard américain" },
    { name: "Loganberry" },
    { name: "Lotus" },
    { name: "Lotus sacré" },
    { name: "Lupin blanc" },
    { name: "Épinards de Malabar" },
    { name: "Pomme mammee" },
    { name: "Mangouse violet" },
    { name: "Alpine Sweetvetch" },
    { name: "Poisson-lait" },
    { name: "La lotte" },
    { name: "Haricot" },
    { name: "Montagne Yam" },
    { name: "Mulet rayé" },
    { name: "Moutarde blanche" },
    { name: "Épinards de moutarde" },
    { name: "Épinards néo-zélandais" },
    { name: "Nopal" },
    { name: "Ocean Pout" },
    { name: "Gombo" },
    { name: "Tuniqué" },
    { name: "Autruche" },
    { name: "Hareng du Pacifique" },
    { name: "Huître du Pacifique" },
    { name: "Rasfish du Pacifique" },
    { name: "Canard de velours" },
    { name: "Persimmon commun" },
    { name: "Faisan" },
    { name: "Nord du brochet" },
    { name: "Noix de plili" },
    { name: "Colorado Pinyon" },
    { name: "Pittanga" },
    { name: "Plaines de barbarie de la poire" },
    { name: "Plantain français" },
    { name: "Pokeweed américain" },
    { name: "Grain d'opium" },
    { name: "Turnip Prairie" },
    { name: "Figue de Barbarie" },
    { name: "quinoa" },
    { name: "Lapin européen" },
    { name: "Arc-en-ciel" },
    { name: "truite arc-en-ciel" },
    { name: "Prune de Malabar" },
    { name: "Rose hanche" },
    { name: "Roselle" },
    { name: "Orange rugueux" },
    { name: "Poisson-de-matières" },
    { name: "Saumon rose" },
    { name: "Chaum saumon" },
    { name: "Saumon coho" },
    { name: "Saumon rouge" },
    { name: "Saumon chinook" },
    { name: "Saumon atlantique" },
    { name: "Salmonier" },
    { name: "Salsification commune" },
    { name: "Sapodilla" },
    { name: "Mamey Sapote" },
    { name: "Maquereau espagnol" },
    { name: "Sardine du Pacifique" },
    { name: "Coquille" },
    { name: "Scpuce" },
    { name: "Concombre de mer" },
    { name: "Steller Sea Lion" },
    { name: "Joint barbu" },
    { name: "Sceau annulé" },
    { name: "Truite de mer" },
    { name: "Fleur de Sesbanie" },
    { name: "Requin" },
    { name: "Sheefish" },
    { name: "Mouton" },
    { name: "Agneau" },
    { name: "Tête de mouton" },
    { name: "Moutarde de haie" },
    { name: "Tuna de listaon" },
    { name: "Snaper" },
    { name: "Sursope" },
    { name: "Des sorts" },
    { name: "Spiruline" },
    { name: "Pigeonneau" },
    { name: "Goyava à la fraise" },
    { name: "Plus grand esturgeon" },
    { name: "Ventouse blanche" },
    { name: "Pomme de sucre" },
    { name: "Saine de la citrouille" },
    { name: "Espadon" },
    { name: "Taro" },
    { name: "Teff" },
    { name: "Poisson-tuile" },
    { name: "Secourrière mexicaine" },
    { name: "Serviette gourde" },
    { name: "Salmonidés (saumon, truite)" },
    { name: "Turquie" },
    { name: "Bovins (boeuf, veau)" },
    { name: "Doré" },
    { name: "goberge de l'Alaska" },
    { name: "Wasabi" },
    { name: "Gourde de cire" },
    { name: "Buccin" },
    { name: "Pollock de poissons" },
    { name: "Corveau large" },
    { name: "Poisson blanc" },
    { name: "Merlan" },
    { name: "Riz sauvage" },
    { name: "Willow de la feuille de thé" },
    { name: "Haricotement" },
    { name: "patate douce" },
    { name: "Jicama" },
    { name: "Yautia." },
    { name: "Thon jaune" },
    { name: "Yellowtail Amberjack" },
    { name: "Bonder" },
    { name: "Thon blanc" },
    { name: "Gadus (code commun)" },
    { name: "Halibut de l'Atlantique" },
    { name: "Flétan pacifique" },
    { name: "Saumon du Pacifique" },
    { name: "Éperlan" },
    { name: "Clupeinae (hareng, sardine, sprat)" },
    { name: "Homard épineux" },
    { name: "Crabe des neiges" },
    { name: "Pois aux yeux noirs" },
    { name: "Cerf" },
    { name: "Noix de macadamia" },
    { name: "Percoidei (basse et autres)" },
    { name: "Perciformes" },
    { name: "Lapin" },
    { name: "Chèvre domestique" },
    { name: "Beefalo" },
    { name: "Bivespace (palourdes, moules, huîtres)" },
    { name: "Calmar" },
    { name: "Crevette" },
    { name: "Écrevisse" },
    { name: "Poisson plat" },
    { name: "Cochon domestique" },
    { name: "Morse" },
    { name: "Rhubarbe sauvage de l'Alaska" },
    { name: "Blé oriental" },
    { name: "Haricot de yardlong" },
    { name: "Caille" },
    { name: "Boysenberry" },
    { name: "Chaux persane" },
    { name: "Feijoa" },
    { name: "Rangée" },
    { name: "Oreille du Juif" },
    { name: "Champignon commun" },
    { name: "Shiitake" },
    { name: "Violet faire" },
    { name: "Wakame" },
    { name: "Énouvre" },
    { name: "Épouse" },
    { name: "pleurotes" },
    { name: "Fungus de l'oreille de nuage" },
    { name: "Touïcade" },
    { name: "Fern d'autruche" },
    { name: "Spot Croker" },
    { name: "Sourriolock" },
    { name: "Ware." },
    { name: "Ménhaden atlantique" },
    { name: "Blé" },
    { name: "Chokérrie commune" },
    { name: "Agave" },
    { name: "Cattail narroueaf" },
    { name: "Méduse" },
    { name: "Anchois" },
    { name: "Whiting bleu" },
    { name: "Brel carpe" },
    { name: "Chanterelle" },
    { name: "Esturgeon" },
    { name: "Auto" },
    { name: "Canelle" },
    { name: "Crabe" },
    { name: "Pelote commune" },
    { name: "Aiguillette épineuse" },
    { name: "Anatidae" },
    { name: "Anguilliformes" },
    { name: "Grenouille" },
    { name: "Orphie" },
    { name: "Gadiformes" },
    { name: "Lièvre de montagne" },
    { name: "truite de lac" },
    { name: "Semelle au citron" },
    { name: "Homard griffé" },
    { name: "Mordu" },
    { name: "Scombridae (Nice, Maquereau, Tuna)" },
    { name: "Moules marines" },
    { name: "Norvège Haddock" },
    { name: "Norvège homard" },
    { name: "Norvège Pout" },
    { name: "Huile de palme" },
    { name: "Véritable huître" },
    { name: "Paume de sago" },
    { name: "Plongeon" },
    { name: "Pikeperch" },
    { name: "Pléuronectides (dab, flétan, plie)" },
    { name: "Rock ptarmigan" },
    { name: "Perche de l'océan Pacifique" },
    { name: "Salsification noire" },
    { name: "True Sceau" },
    { name: "Algues rouges" },
    { name: "Kombu" },
    { name: "Escargot" },
    { name: "True Sole" },
    { name: "Poisson-chat" },
    { name: "Chardon" },
    { name: "Thunnus" },
    { name: "noyer" },
    { name: "Cétacée (dauphin, marsouin, baleine)" },
    { name: "Columbidae (colombe, pigeon)" },
    { name: "Conque" },
    { name: "Vin de raisin" },
    { name: "Vin de baies" },
    { name: "Autre vin" },
    { name: "Cidre" },
    { name: "Alcool" },
    { name: "Fromage" },
    { name: "Vache laitière)" },
    { name: "Œufs" },
    { name: "Yaourt" },
    { name: "Haricot" },
    { name: "Vodka" },
    { name: "Whisky" },
    { name: "Glace" },
    { name: "Gin" },
    { name: "Chéri" },
    { name: "Réglisse" },
    { name: "Le vinaigre" },
    { name: "Salle" },
    { name: "Porto" },
    { name: "Vermouth" },
    { name: "Sherry" },
    { name: "Vin de vin" },
    { name: "Nougat" },
    { name: "Caramel au beurre" },
    { name: "Gâteau" },
    { name: "Pizza" },
    { name: "Jouxillement" },
    { name: "Autres collations" },
    { name: "Pain croustillant" },
    { name: "Pâtisserie" },
    { name: "Dragée" },
    { name: "Chewing-gum" },
    { name: "Massepain" },
    { name: "Vinaigrette" },
    { name: "sauce" },
    { name: "Sel" },
    { name: "Le beurre" },
    { name: "Substitut au beurre" },
    { name: "Crème" },
    { name: "Sucre" },
    { name: "Saucisson" },
    { name: "Boulette de viande" },
    { name: "Moutarde" },
    { name: "Crâne" },
    { name: "Substitut du sucre" },
    { name: "Bouillon de viande" },
    { name: "Petit lait" },
    { name: "Caséine" },
    { name: "Conserve des fruits" },
    { name: "Agence levée" },
    { name: "Guimauve" },
    { name: "Gélatine" },
    { name: "Eau" },
    { name: "Autre produit de poisson" },
    { name: "Lait (humain)" },
    { name: "Autres boissons" },
    { name: "Nourriture pour bébés" },
    { name: "Boulette" },
    { name: "Soupe" },
    { name: "Autre produit de légumes" },
    { name: "Nourriture ou boisson non classée" },
    { name: "Sirop" },
    { name: "Suif" },
    { name: "Rémoulade." },
    { name: "Pâte à tartiner" },
    { name: "Gomme de fruits" },
    { name: "poudre de curry" },
    { name: "Autres bonbons" },
    { name: "Meringue" },
    { name: "Saindoux" },
    { name: "Autre graisse animale" },
    { name: "Autre produit de cacao" },
    { name: "Le beurre de cacao" },
    { name: "Poudre de cacao" },
    { name: "Liqueur de cacao" },
    { name: "Chocolat" },
    { name: "Chocolat chaud" },
    { name: "Lait séché" },
    { name: "Lait (autres mammifères)" },
    { name: "Kéfir" },
    { name: "Babeurre" },
    { name: "Autre lait fermenté" },
    { name: "Je suis la sauce" },
    { name: "Miso" },
    { name: "Tofu" },
    { name: "biscotte" },
    { name: "Chevreuil" },
    { name: "Tilapia" },
    { name: "glaçage" },
    { name: "Snack-bar" },
    { name: "Tortue verte" },
    { name: "Boisson énergisante" },
    { name: "Burrito" },
    { name: "Hamburger" },
    { name: "Haricots cuits au four" },
    { name: "le Chili" },
    { name: "Taco" },
    { name: "Tortilla" },
    { name: "Nachos" },
    { name: "Fromage fondu" },
    { name: "salade" },
    { name: "Substitut de la crème" },
    { name: "Caramel" },
    { name: "Garniture" },
    { name: "Souple crème" },
    { name: "Rouleau" },
    { name: "Coeur de palmier" },
    { name: "Pop corn" },
    { name: "Chips de pomme de terre" },
    { name: "Puce de tortilla" },
    { name: "Puce de maïs" },
    { name: "Thé à l'hibiscus" },
    { name: "Ragoût" },
    { name: "Dessert de gélatine" },
    { name: "Voyage" },
    { name: "Falafel" },
    { name: "Frire" },
    { name: "Lasagne" },
    { name: "Crêpe" },
    { name: "Pectine" },
    { name: "Pudding" },
    { name: "Gaufre" },
    { name: "Je suis du lait" },
    { name: "Pain de viande" },
    { name: "Saké" },
    { name: "Cocktail" },
    { name: "Couscous" },
    { name: "Boulgour" },
    { name: "Substitut du café" },
    { name: "Café moka" },
    { name: "Chimichanga" },
    { name: "La semoule" },
    { name: "Perles de Tapioca" },
    { name: "Griller" },
    { name: "Quesadilla" },
    { name: "Pomme de terre au four" },
    { name: "Hot-dog" },
    { name: "Propagé" },
    { name: "Enchilada" },
    { name: "Substitut d'œufs" },
    { name: "Boisson nutritionnelle" },
    { name: "Autre sandwich" },
    { name: "Ketchup" },
    { name: "Sandwich au petit-déjeuner" },
    { name: "Pansement" },
    { name: "Macaroni et fromage" },
    { name: "Matière grasse" },
    { name: "Melon cornée" },
    { name: "Hushpuppy" },
    { name: "Jus de fruit" },
    { name: "Goût" },
    { name: "Autre produit de fruit" },
    { name: "Salade de fruit" },
    { name: "Je suis yaourt." },
    { name: "La nourriture végétarienne" },
    { name: "Burger végétarien" },
    { name: "Coupe froide" },
    { name: "Écrous mixtes" },
    { name: "Canola" },
    { name: "Paume de Babassu" },
    { name: "Cupua" },
    { name: "Arbre de karité" },
    { name: "Camélia de graines pétrolières" },
    { name: "Cucuba" },
    { name: "pâte phyllo" },
    { name: "Huile de cuisson" },
    { name: "Croûte de tarte" },
    { name: "Remplissage de tarte" },
    { name: "À" },
    { name: "Raccourcissement" },
    { name: "Je suis crème" },
    { name: "Cornet de glace" },
    { name: "Mélasse" },
    { name: "Biscuit salé" },
    { name: "Nance" },
    { name: "Naranjilla" },
    { name: "Natto" },
    { name: "Ravioli" },
    { name: "Mettre en scène" },
    { name: "Autre plat de pâtes" },
    { name: "Succotash" },
    { name: "Tamale" },
    { name: "Gâteau de riz" },
    { name: "Arbre fou" },
    { name: "Lait évaporé" },
    { name: "Farine" },
    { name: "Acutaq" },
    { name: "Pâte" },
    { name: "Pain pita" },
    { name: "Focaccia" },
    { name: "Beignet" },
    { name: "Autre produit de pain" },
    { name: "PAIN PIKI" },
    { name: "pain perdu" },
    { name: "Pain de blé" },
    { name: "pain de seigle" },
    { name: "Pain d'avoine" },
    { name: "Pain de pommes de terre" },
    { name: "pain au maïs" },
    { name: "Gruau de maïs" },
    { name: "Pain à grains multiples" },
    { name: "Pain de riz" },
    { name: "Pain sucré" },
    { name: "Pain aux raisins" },
    { name: "Wotton Wrapper" },
    { name: "Mélange montagnard" },
    { name: "Jus de légumes" },
    { name: "Horchata" },
    { name: "Boisson non-alcoolisée" },
    { name: "Yaourt glacé" },
    { name: "Milk-shake" },
    { name: "Chocolate mousse" },
    { name: "Égouttage" },
    { name: "Pupusa" },
    { name: "Petit pâté" },
    { name: "Arepa" },
    { name: "Ascrides" },
    { name: "Gefilte poisson" },
    { name: "Pond-lys jaune" },
    { name: "Burger de poisson" },
    { name: "Autre plat" },
    { name: "Je peux tarte" },
    { name: "Rembourrage" },
    { name: "Shell comestible" },
    { name: "Truquer" },
    { name: "Barre de bonbon" },
    { name: "Lait condensé" },
    { name: "Margarine" },
    { name: "Spread de la margarine" },
    { name: "Hoummous" },
    { name: "Bouffées de pommes de terre" },
    { name: "Gratin dauphinois" },
    { name: "Substitut de lait" },
    { name: "Poivre (C. Pubescens)" },
    { name: "Ail à col doux" },
    { name: "Choux" },
    { name: "Bayberry chinois" },
    { name: "Champignons" },
    { name: "Breuvages alcoolisés" },
    { name: "Légumes d'oignon-famille" },
    { name: "Pommes" },
    { name: "Brassicas" },
    { name: "Céréales et produits de céréales" },
    { name: "Agrumes" },
    { name: "Cacao et produits de cacao" },
    { name: "Café et café Products" },
    { name: "Crustacés" },
    { name: "Lait et produits laitiers" },
    { name: "Graisses et huiles" },
    { name: "Des poissons" },
    { name: "Herbes et épices" },
    { name: "Impulsions" },
    { name: "Mollusques" },
    { name: "Des noisettes" },
    { name: "Breuvages" },
    { name: "Fruits" },
    { name: "Légumes verts" },
    { name: "Légumes racines" },
    { name: "Sunburst Squash (Squash Pattypan)" },
    { name: "Courgette verte" },
    { name: "Courgettes jaunes" },
    { name: "Poivron vert" },
    { name: "Poivron jaune" },
    { name: "Poivron orange" },
    { name: "poivron rouge" },
    { name: "Poivron rouge doux italien" },
    { name: "Haricot de cire jaune" },
    { name: "Haricot vert" },
    { name: "Saskatoon Berry" },
    { name: "Cerise nanking" },
    { name: "Citrouille japonaise" },
    { name: "chou blanc" },
    { name: "laitue romaine" },
    { name: "Lait de vache" },
    { name: "Myrtille rabbiteye" },
    { name: "Yali poire" },
    { name: "Asperges Racemosus" },
    { name: "Fern d'asperges" },
    { name: "Mûre" },
    { name: "mûre" },
    { name: "Thé noir" },
    { name: "Thé vert" },
    { name: "Huile d'olive" },
    { name: "Macroalgae" },
    { name: "vin rouge" },
    { name: "Huile de lin" },
    { name: "Huile de colza" },
    { name: "Huile de soja" },
    { name: "Guarana" },
    { name: "Copain" },
    { name: "vin blanc" },
    { name: "Orange aigre" },
    { name: "Jaune d'œuf" },
    { name: "Vin rosé" },
    { name: "Mûrier blanche" },
    { name: "Huile de canola" },
    { name: "Vin de dessert" },
    { name: "Champagne rouge" },
    { name: "thé rouge" },
    { name: "Champagne blanc" },
    { name: "Jus de raisin rouge" },
    { name: "Jus de raisin blanc" },
    { name: "Crosse" },
    { name: "trèfle rouge" },
    { name: "Baies de perdrix" },
    { name: "Mikan" },
    { name: "Fromage mozzarella" },
    { name: "Fromage à la crème" },
    { name: "Fromage cheddar" },
    { name: "parmesan" },
    { name: "Lait d'amande" },
    { name: "Lait de coco" },
    { name: "Beurre salé" },
    { name: "Huile de tournesol" },
    { name: "Huile de noix de coco" },
    { name: "Huile d'arachide" },
    { name: "Huile de coton" },
    { name: "Huile de pépins de raisin" },
    { name: "Huile de sésame" },
    { name: "Monterey Jack Cheese" },
    { name: "fromage suisse" },
    { name: "Cottage cheese" },
    { name: "Fromage bleu" },
    { name: "Palourde" },
    { name: "Crème aigre" },
    { name: "Pain de blé entier" },
    { name: "Piment jalapeno" },
    { name: "Feta" },
    { name: "Eddoe" },
    { name: "Banane plantain" },
    { name: "Clémentine" },
    { name: "Pomme verte" },
    { name: "oignon blanc" },
    { name: "oignon rouge" },
    { name: "Oignon vert" },
    { name: "raisin rouge" },
    { name: "Prune noire" },
    { name: "Chou vert" },
    { name: "Raisin noir" },
    { name: "Haricot de cannellini" },
    { name: "Lentilles verte" },
    { name: "Poivron cubanelle" },
    { name: "Laitue iceberg" },
    { name: "Pousses de pois" },
    { name: "Yau choy" },
    { name: "Prune verte" },
    { name: "Wampee" },
    { name: "Pitaya" },
    { name: "Goji" },
    { name: "Aubépine" },
    { name: "Lanterne" },
    { name: "Pain blanc" },
    { name: "Thé aux herbes" },
    { name: "Huile de poisson" },
  ];

  const tag = await prisma.type.create({
    data: { name: "Carnivore" },
  });

  const entree = await prisma.type.create({
    data: { name: "Entrée" },
  });

  const types = [{ name: "Plat" }, { name: "Dessert" }];

  const users = [
    {
      name: "Owner1234",
      email: "owner1234@yopmail.com",
      password: "123456",
    },
    {
      name: "Owner2345",
      email: "owner2345@yopmail.com",
      password: "123456",
    },
    {
      name: "Owner3456",
      email: "owner3456@yopmail.com",
      password: "123456",
    },
  ];

  const gramme = await prisma.unit.create({
    data: { name: "gr" },
  });

  const units = [
    {
      name: "L",
    },
    {
      name: "Cl",
    },
    {
      name: "Ml",
    },
    {
      name: "cuillère à soupe",
    },
    {
      name: "cuillère à café",
    },
    {
      name: "unité",
    },
    {
      name: "tasse",
    },
  ];

  const couscous = await prisma.dish.create({
    data: {
      title: "Couscous",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      description:
        "pgAdmin is the most popular and feature rich Open Source administration and development platform for PostgreSQL, the most advanced Open Source  in the world.",
      regionId: afrique.id,
    },
  });

  const dishes = [
    {
      title: "Pot au Feu à l'ancienne",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      description:
        "Over the past two decades, Rails has taken countless companies to millions of users and billions in market valuations.",
      regionId: afrique.id,
    },
    {
      title: "Poutine",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      description: "Sans commentaire.",
      regionId: afrique.id,
    },
  ];

  const recipe = await prisma.recipe.create({
    data: {
      name: "Couscous en mode blanquette",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      cookId: john.id,
      dishId: couscous.id,
      typeId: entree.id,
      countryId: maroc.id,
      persons: 4,
    },
  });

  const list = await prisma.list.create({
    data: {
      name: "À essayer",
      userId: john.id,
      recipes: {
        connect: [{ id: recipe.id }],
      },
    },
  });

  const recipes = [
    {
      name: "Couscous de chez ma grand mère",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      cookId: john.id,
      dishId: couscous.id,
      typeId: entree.id,
      countryId: maroc.id,
      persons: 10,
    },
    {
      name: "Un autre couscous incroyable",
      imageUrl:
        "https://images.unsplash.com/photo-1541518763669-27fef04b14ea?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1033&q=80",
      cookId: john.id,
      dishId: couscous.id,
      typeId: entree.id,
      countryId: maroc.id,
      persons: 2,
    },
  ];

  const comments = [
    {
      text: "Testé et approuvé !",
      userId: john.id,
      recipeId: recipe.id,
    },
    {
      text: "En fait j'ai détesté !",
      userId: john.id,
      recipeId: recipe.id,
    },
  ];

  https: await prisma.user.createMany({
    data: users,
  });

  await prisma.tag.createMany({
    data: tags,
  });

  await prisma.country.createMany({
    data: countries,
  });

  await prisma.type.createMany({
    data: types,
  });

  await prisma.region.createMany({
    data: regions,
  });

  await prisma.ingredient.createMany({
    data: ingredients,
  });

  await prisma.dish.createMany({
    data: dishes,
  });

  await prisma.recipe.createMany({
    data: recipes,
  });

  await prisma.unit.createMany({
    data: units,
  });

  await prisma.comment.createMany({
    data: comments,
  });
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });